apiVersion: v1
kind: Service
metadata:
  name: cyy-svc
  namespace: cyy
spec:
  selector:
    app: cyy
  type: ClusterIP
  ports:
    - name: cyy-svc-http-port
      port: 8080
      targetPort: 8080

